#!/usr/bin/env python3

import os
import sys
import datetime

# Print the HTTP headers
print("Content-Type: text/html")
print("") # Empty line to separate headers from body

# Print the HTML page
print("""<!DOCTYPE html>
<html>
<head>
    <title>CGI Test</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        h1 {{
            color: #0A2342;
        }}
        .info {{
            background-color: #f5f7fa;
            border: 1px solid #ddd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }}
        .env {{
            background-color: #f0f0f0;
            padding: 10px;
            border-radius: 5px;
            font-family: monospace;
            overflow-x: auto;
        }}
    </style>
</head>
<body>
    <h1>Hello from CGI!</h1>
    <div class="info">
        <p>This page was generated by a Python CGI script.</p>
        <p>Current time: {}</p>
    </div>
    
    <h2>Environment Information</h2>
    <div class="env">""".format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")))

# Print environment variables
print("<h3>CGI Environment Variables:</h3>")
print("<ul>")
for variable in sorted(os.environ.keys()):
    if variable.startswith(("HTTP_", "REQUEST_", "QUERY_", "SCRIPT_", "PATH_")):
        print("<li>{}: {}</li>".format(variable, os.environ.get(variable, "")))
print("</ul>")

# Print request details
print("<h3>Request Method:</h3>")
print("<p>{}</p>".format(os.environ.get("REQUEST_METHOD", "Unknown")))

# If this is a POST request, print the POST data
if os.environ.get("REQUEST_METHOD") == "POST":
    content_length = int(os.environ.get("CONTENT_LENGTH", 0))
    if content_length > 0:
        post_data = sys.stdin.read(content_length)
        print("<h3>POST Data:</h3>")
        print("<pre>{}</pre>".format(post_data))

# Close the HTML tags
print("""    </div>
</body>
</html>""") 